// Generated by scripts/generate-template-package.ts. Do not edit by hand.
export const TEMPLATE_PACKAGE_VERSIONS = {
  dependencies: {
    "@lambdaimg/alchemy": "^0.1.0",
    alchemy: "2.0.0-beta.58",
    effect: "^4.0.0-beta.90",
  },
  devDependencies: {
    "@effect/platform-bun": "^4.0.0-beta.90",
    "@types/node": "^26.0.1",
    typescript: "^5.9.3",
  },
} as const;
