import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

interface PackageJson {
  version?: string;
  dependencies?: Record<string, string>;
  devDependencies?: Record<string, string>;
  workspaces?: {
    catalog?: Record<string, string>;
  };
}

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(scriptDir, "../../..");
const outputPath = path.resolve(scriptDir, "../src/template-package.generated.ts");

const [rootPackage, alchemyPackage, generatedAppPackage] = await Promise.all([
  readPackageJson(path.join(repoRoot, "package.json")),
  readPackageJson(path.join(repoRoot, "packages/alchemy/package.json")),
  readPackageJson(path.join(repoRoot, "examples/generated-app/package.json")),
]);

const effectVersion = required(
  alchemyPackage.dependencies?.effect,
  "packages/alchemy/package.json dependency effect",
);

const templatePackageVersions = {
  dependencies: {
    "@lambdaimg/alchemy": applyRangePrefix(
      required(
        generatedAppPackage.dependencies?.["@lambdaimg/alchemy"],
        "examples/generated-app/package.json dependency @lambdaimg/alchemy",
      ),
      required(alchemyPackage.version, "packages/alchemy/package.json version"),
    ),
    alchemy: required(
      alchemyPackage.dependencies?.alchemy,
      "packages/alchemy/package.json dependency alchemy",
    ),
    effect: applyRangePrefix(
      required(
        generatedAppPackage.dependencies?.effect,
        "examples/generated-app/package.json dependency effect",
      ),
      effectVersion,
    ),
  },
  devDependencies: {
    "@effect/platform-bun": applyRangePrefix(
      required(
        generatedAppPackage.devDependencies?.["@effect/platform-bun"],
        "examples/generated-app/package.json devDependency @effect/platform-bun",
      ),
      effectVersion,
    ),
    "@types/node": required(
      rootPackage.workspaces?.catalog?.["@types/node"],
      "root catalog @types/node",
    ),
    typescript: required(
      generatedAppPackage.devDependencies?.typescript,
      "examples/generated-app/package.json devDependency typescript",
    ),
  },
};

await writeFile(
  outputPath,
  `// Generated by scripts/generate-template-package.ts. Do not edit by hand.
export const TEMPLATE_PACKAGE_VERSIONS = {
  dependencies: ${formatRecord(templatePackageVersions.dependencies, 2)},
  devDependencies: ${formatRecord(templatePackageVersions.devDependencies, 2)},
} as const;
`,
);

async function readPackageJson(packagePath: string): Promise<PackageJson> {
  return JSON.parse(await readFile(packagePath, "utf8")) as PackageJson;
}

function required(value: string | undefined, label: string): string {
  if (!value) {
    throw new Error(`Missing ${label}.`);
  }
  return value;
}

function applyRangePrefix(referenceRange: string, version: string): string {
  const prefix = referenceRange.match(/^[~^]/)?.[0] ?? "";
  return `${prefix}${version.replace(/^[~^]/, "")}`;
}

function formatRecord(record: Record<string, string>, indent: number): string {
  const currentIndent = " ".repeat(indent);
  const nestedIndent = " ".repeat(indent + 2);
  const entries = Object.entries(record)
    .map(([key, value]) => `${nestedIndent}${formatKey(key)}: ${JSON.stringify(value)},`)
    .join("\n");
  return `{\n${entries}\n${currentIndent}}`;
}

function formatKey(key: string): string {
  return /^[A-Za-z_$][\w$]*$/.test(key) ? key : JSON.stringify(key);
}
